#!/bin/bash
echo "Enter a number"
read a
x=$a
sum=0
m=0
n=0
while [ $x -gt 0 ]
do
m=`expr $x % 10`
n=`expr $m \* $m \* $m`
sum=`expr $sum + $n`
x=`expr $x / 10`
done
if [ $sum -eq $a ]
then
echo "It is an Armstrong number"
else
echo "it is not  Asrmstrong number"
fi
